# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lx < Formula
  desc "Git-aware tmux session manager with worktree support (client/server)"
  homepage "https://github.com/sibhod/homebrew-lx"
  version "1.1.2"
  license "ISC"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sibhod/homebrew-lx/releases/download/v1.1.2/lx_1.1.2_darwin_amd64.tar.gz"
      sha256 "20491fb372a4fbea6bef8c07173aa5ba901331b5149c0f795bec4b3efaf70fd4"

      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
        # The bundled unit ships the from-source ExecStart (%h/.local/bin/lx-server,
        # from deploy/scripts/install-server.sh). Rewrite it to the brew-managed
        # binary so `systemctl --user enable --now lx-server` works for a Homebrew
        # install. opt_bin is upgrade-stable (the opt/ symlink tracks the linked
        # version), so a user's copied unit keeps working across `brew upgrade`. (lx-vgv)
        inreplace "#{pkgshare}/lx-server.service", "%h/.local/bin/lx-server", "#{opt_bin}/lx-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sibhod/homebrew-lx/releases/download/v1.1.2/lx_1.1.2_darwin_arm64.tar.gz"
      sha256 "dbfdf3f1dc954e241d7b4427188e5496bd84b314f5e0b53a33c900124e5e9c5d"

      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
        # The bundled unit ships the from-source ExecStart (%h/.local/bin/lx-server,
        # from deploy/scripts/install-server.sh). Rewrite it to the brew-managed
        # binary so `systemctl --user enable --now lx-server` works for a Homebrew
        # install. opt_bin is upgrade-stable (the opt/ symlink tracks the linked
        # version), so a user's copied unit keeps working across `brew upgrade`. (lx-vgv)
        inreplace "#{pkgshare}/lx-server.service", "%h/.local/bin/lx-server", "#{opt_bin}/lx-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sibhod/homebrew-lx/releases/download/v1.1.2/lx_1.1.2_linux_amd64.tar.gz"
      sha256 "fed8af06ea3cb9c81e907b905eb6e65f3a3ea4fb73488224c8b2c060804c6628"
      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
        # The bundled unit ships the from-source ExecStart (%h/.local/bin/lx-server,
        # from deploy/scripts/install-server.sh). Rewrite it to the brew-managed
        # binary so `systemctl --user enable --now lx-server` works for a Homebrew
        # install. opt_bin is upgrade-stable (the opt/ symlink tracks the linked
        # version), so a user's copied unit keeps working across `brew upgrade`. (lx-vgv)
        inreplace "#{pkgshare}/lx-server.service", "%h/.local/bin/lx-server", "#{opt_bin}/lx-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sibhod/homebrew-lx/releases/download/v1.1.2/lx_1.1.2_linux_arm64.tar.gz"
      sha256 "19f80087bd4b5a71248295aeb12440c0ceb9c8ff565949f4d5f03c6a7ef55f0e"
      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
        # The bundled unit ships the from-source ExecStart (%h/.local/bin/lx-server,
        # from deploy/scripts/install-server.sh). Rewrite it to the brew-managed
        # binary so `systemctl --user enable --now lx-server` works for a Homebrew
        # install. opt_bin is upgrade-stable (the opt/ symlink tracks the linked
        # version), so a user's copied unit keeps working across `brew upgrade`. (lx-vgv)
        inreplace "#{pkgshare}/lx-server.service", "%h/.local/bin/lx-server", "#{opt_bin}/lx-server"
      end
    end
  end

  def caveats
    <<~EOS
      lx is a client/server app: the `lx` client talks to an lx-server over an
      SSH-tunnelled unix socket.

      On the SERVER box (Linux), enable the daemon as a systemd --user service:
        mkdir -p ~/.config/systemd/user
        cp #{opt_pkgshare}/lx-server.service ~/.config/systemd/user/
        systemctl --user daemon-reload
        systemctl --user enable --now lx-server

      lx-server is Linux-only; on macOS `lx` runs purely as a client to a remote
      Linux server. Connect a project with `lx connect <path>`, then `lx <project>`.
    EOS
  end

  test do
    system "#{bin}/lx", "--help"
  end
end
