# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lx < Formula
  desc "Git-aware tmux session manager with worktree support (client/server)"
  homepage "https://github.com/sibhod/homebrew-lx"
  version "1.1.1"
  license "ISC"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sibhod/homebrew-lx/releases/download/v1.1.1/lx_1.1.1_darwin_amd64.tar.gz"
      sha256 "2c8b38f04c87dea74ee6a5dbcc890a2b7bd0c968edc1b415c9c5e8d8fa0ca8ae"

      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sibhod/homebrew-lx/releases/download/v1.1.1/lx_1.1.1_darwin_arm64.tar.gz"
      sha256 "86f439f1d8aa9257467e4c381feacd83e89eede86b544632f25f982a91a34990"

      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sibhod/homebrew-lx/releases/download/v1.1.1/lx_1.1.1_linux_amd64.tar.gz"
      sha256 "254bae86e84fbd80fe080be6dee148124a6c3cee1ac9a6d3169f59f108e54868"
      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sibhod/homebrew-lx/releases/download/v1.1.1/lx_1.1.1_linux_arm64.tar.gz"
      sha256 "4505aefbc2373eceb464a7cde5ab081f1aa70646f718fc107b88c55bc26ecec7"
      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
      end
    end
  end

  def caveats
    <<~EOS
      lx is a client/server app: the `lx` client talks to an lx-server over an
      SSH-tunnelled unix socket.

      On the SERVER box (Linux), enable the daemon as a systemd --user service:
        mkdir -p ~/.config/systemd/user
        cp #{opt_pkgshare}/lx-server.service ~/.config/systemd/user/
        systemctl --user daemon-reload
        systemctl --user enable --now lx-server

      lx-server is Linux-only; on macOS `lx` runs purely as a client to a remote
      Linux server. Connect a project with `lx connect <path>`, then `lx <project>`.
    EOS
  end

  test do
    system "#{bin}/lx", "--help"
  end
end
