# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lx < Formula
  desc "Git-aware tmux session manager with worktree support (client/server)"
  homepage "https://github.com/sibhod/loomux"
  version "1.1.0"
  license "ISC"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sibhod/loomux/releases/download/v1.1.0/lx_1.1.0_darwin_amd64.tar.gz"
      sha256 "0db9d31525643c68c92c4fc2cdbfbe5e27fb91516d90ade3d163d7fda37320f3"

      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sibhod/loomux/releases/download/v1.1.0/lx_1.1.0_darwin_arm64.tar.gz"
      sha256 "237a93336c2d12ba93a0c8fc6ccda5605fc9cad4e78ff421df4ae235b551187b"

      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sibhod/loomux/releases/download/v1.1.0/lx_1.1.0_linux_amd64.tar.gz"
      sha256 "a7d89926b11446d2c2556d5bfa97e39e29640940d31f9a0d7d0db6b3362d1a8d"
      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sibhod/loomux/releases/download/v1.1.0/lx_1.1.0_linux_arm64.tar.gz"
      sha256 "db8749bdb67cf8981c36c1bf37ae7e17f890e4466de2cb92b3a05fb2665e0dce"
      define_method(:install) do
        bin.install "lx", "lx-server", "lx-agent-hook"
        pkgshare.install "deploy/systemd/lx-server.service"
      end
    end
  end

  def caveats
    <<~EOS
      lx is a client/server app: the `lx` client talks to an lx-server over an
      SSH-tunnelled unix socket.

      On the SERVER box (Linux), enable the daemon as a systemd --user service:
        mkdir -p ~/.config/systemd/user
        cp #{opt_pkgshare}/lx-server.service ~/.config/systemd/user/
        systemctl --user daemon-reload
        systemctl --user enable --now lx-server

      lx-server is Linux-only; on macOS `lx` runs purely as a client to a remote
      Linux server. Connect a project with `lx connect <path>`, then `lx <project>`.
    EOS
  end

  test do
    system "#{bin}/lx", "--help"
  end
end
