# This file was generated by GoReleaser. DO NOT EDIT.
cask "lx" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "cdf25eb43418c87df238b14f209769dc6a79d8edaa7ce42faa6aee0501e6623c"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc794d83b3184bd0117b19c91ab433dd4bff76d3131c22a9892d4d8df4a4bf8e"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3696a88384edb8a4ad4ccd7fafd985d7764ef89039cebb227ca8ff96c04fd1cd"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "737abbe86565cc59b2265c1f7ee8f4f46b1317cec54b107652e0284099a0e3ef"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lx"
  desc "Git-aware tmux session manager with worktree support (client/server)"
  homepage "https://github.com/sibhod/homebrew-lx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lx"
  binary "lx-server"
  binary "lx-agent-hook"

  postflight do
    if OS.mac?
      ["lx", "lx-server", "lx-agent-hook"].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    elsif OS.linux?
      system_command "/usr/bin/sed",
                     args: ["-i", "s|%h/.local/bin/lx-server|#{HOMEBREW_PREFIX}/bin/lx-server|",
                            "#{staged_path}/deploy/systemd/lx-server.service"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    lx is a client/server app: the `lx` client talks to an lx-server over an
    SSH-tunnelled unix socket.

    On the SERVER box (Linux), enable the daemon as a systemd --user service:
      mkdir -p ~/.config/systemd/user
      cp #{staged_path}/deploy/systemd/lx-server.service ~/.config/systemd/user/
      systemctl --user daemon-reload
      systemctl --user enable --now lx-server

    lx-server is Linux-only; on macOS `lx` runs purely as a client to a remote
    Linux server. Connect a project with `lx connect <path>`, then `lx <project>`.
  EOS
end
