# This file was generated by GoReleaser. DO NOT EDIT.
cask "lx" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "ea566a347038be4cee220ebed1da969772147155e136c712df080165c2de6d3a"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4522ea4b7b3a1dfe2164a09103e5d87135ca018970abdf51a24e63364008d2eb"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8251ddab528b1d71a83a41020b0b19f803ce7d01441837294df5672528bf5ec2"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbe6d654aa62a68b8a5d91d2d3417a2266311bc7730f658326b0ed463ef8f631"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lx"
  desc "Git-aware tmux session manager with worktree support (client/server)"
  homepage "https://github.com/sibhod/homebrew-lx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lx"
  binary "lx-server"
  binary "lx-agent-hook"

  postflight do
    if OS.mac?
      ["lx", "lx-server", "lx-agent-hook"].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    elsif OS.linux?
      system_command "/usr/bin/sed",
                     args: ["-i", "s|%h/.local/bin/lx-server|#{HOMEBREW_PREFIX}/bin/lx-server|",
                            "#{staged_path}/deploy/systemd/lx-server.service"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    lx is a client/server app: the `lx` client talks to an lx-server over an
    SSH-tunnelled unix socket.

    On the SERVER box (Linux), enable the daemon as a systemd --user service:
      mkdir -p ~/.config/systemd/user
      cp #{staged_path}/deploy/systemd/lx-server.service ~/.config/systemd/user/
      systemctl --user daemon-reload
      systemctl --user enable --now lx-server

    lx-server is Linux-only; on macOS `lx` runs purely as a client to a remote
    Linux server. Connect a project with `lx connect <path>`, then `lx <project>`.
  EOS
end
