# This file was generated by GoReleaser. DO NOT EDIT.
cask "lx" do
  version "1.5.0-alpha.3"

  on_macos do
    on_intel do
      sha256 "952d7bc1cbedbfba320b766b0a3275a8af2a1d0f26cda80393f1a66f5b5a7474"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2800b877ee263db60ef5041ec6a0a4551256e243266cd05a19be7c8b5dabcebd"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc681e33fa30d632a7368032caa2a7352067fff4ade955a4be90bb4ee72d44e5"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "85ecfcaf3d1fe558271ee00034bad349a3d16516941c5c030782c0401c96cd01"
      url "https://github.com/sibhod/homebrew-lx/releases/download/v#{version}/lx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lx"
  desc "Git-aware tmux session manager with worktree support (client/server)"
  homepage "https://github.com/sibhod/homebrew-lx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lx"
  binary "lx-server"
  binary "lx-agent-hook"

  postflight do
    if OS.mac?
      ["lx", "lx-server", "lx-agent-hook"].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    elsif OS.linux?
      system_command "/usr/bin/sed",
                     args: ["-i", "s|%h/.local/bin/lx-server|#{HOMEBREW_PREFIX}/bin/lx-server|",
                            "#{staged_path}/deploy/systemd/lx-server.service"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    lx is a client/server app: the `lx` client talks to an lx-server over an
    SSH-tunnelled unix socket.

    On the SERVER box (Linux), enable the daemon as a systemd --user service:
      mkdir -p ~/.config/systemd/user
      cp #{staged_path}/deploy/systemd/lx-server.service ~/.config/systemd/user/
      systemctl --user daemon-reload
      systemctl --user enable --now lx-server

    lx-server is Linux-only; on macOS `lx` runs purely as a client to a remote
    Linux server. Connect a project with `lx connect <path>`, then `lx <project>`.
  EOS
end
